name: envadvntr
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python=2.7.15
  - setuptools=44.0.0
  - matplotlib=2.2.5
  - biopython=1.78
  - pysam=0.15.0
  - cython=0.29.15
  - networkx=1.11
  - scipy=1.5.4
  - joblib=0.14.1
  - scikit-learn=0.20.4
  - numpy=1.16.5
  - tk=8.6.13
  - pip=20.1.1
  - zlib=1.2.13
  - samtools=1.18
  - muscle=3.8.1551
